// Generated by CoffeeScript 1.10.0
(function() {
  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "location": {
      "lat": "double",
      "lon": "double"
    },
    "heading": "string",
    "altitude": "uint",
    "accelerometer": {
      "x": "double",
      "y": "double",
      "z": "double"
    },
    "distance": "string",
    "battery": "string",
    "ignition": "boolean",
    "speed": "string",
    "acceleration": "string",
    "RPM": "string",
    "movement": {
      "idle": "timespan",
      "moving": "timespan"
    },
    "odometer": "string",
    "fuel": {
      "level": "string",
      "efficiency": "string"
    },
    "DTC": ["string"],
    "tow": {
      "state": "boolean",
      "from": {
        "lat": "double",
        "lon": "double"
      }
    },
    "accident": {
      "state": "boolean",
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "harsh": {
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "bus": "{ 1: J1850 VPW, 2: J1850 PWM, 3: ISO9141_2, 4: KWP2000 Fast Init, 5: ISO15765 CAN 11BIT 500KBaud, 6: ISO15765 CAN 29BIT 500KBaud, 7: ISO15765 CAN 11BIT 250KBaud, 8: ISO15765 CAN 29BIT 250KBaud, 9: KWP2000 5-Baud Init }",
    "VIN": "string",
    "GPS": {
      "strength": "string",
      "accuracy": "string",
      "status": "{ 1: 'off', 2: 'searching', 3: 'connected }",
      "satellites": "string"
    },
    "firmware": {
      "version": "string"
    },
    "configuration": {
      "version": "string"
    },
    "sim": {
      "IMSI": "string",
      "connected": "boolean",
      "strength": "string"
    },
    "state": "{ 1: 'sleep', 2: 'waking', 3: 'standby', 4: 'operational' }"
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "bus": "{ 1: J1850 VPW, 2: J1850 PWM, 3: ISO9141_2, 4: KWP2000 Fast Init, 5: ISO15765 CAN 11BIT 500KBaud, 6: ISO15765 CAN 29BIT 500KBaud, 7: ISO15765 CAN 11BIT 250KBaud, 8: ISO15765 CAN 29BIT 250KBaud, 9: KWP2000 5-Baud Init }",
    "battery": "string",
    "VIN": "string",
    "GPS": {
      "strength": "string",
      "accuracy": "string",
      "status": "{ 1: 'off', 2: 'searching', 3: 'connected }",
      "satellites": "string"
    },
    "firmware": {
      "version": "string"
    },
    "configuration": {
      "version": "string"
    },
    "sim": {
      "IMSI": "string",
      "connected": "boolean",
      "strength": "string"
    },
    "state": "{ 1: 'sleep', 2: 'waking', 3: 'standby', 4: 'operational' }"
  });

  ({
    "battery": "string",
    "GPS": {
      "strength": "string",
      "accuracy": "string",
      "status": "{ 1: 'off', 2: 'searching', 3: 'connected }",
      "satellites": "string"
    }
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "location": {
      "lat": "double",
      "lon": "double"
    },
    "heading": "string",
    "altitude": "uint",
    "accelerometer": {
      "x": "double",
      "y": "double",
      "z": "double"
    },
    "distance": "string",
    "battery": "string",
    "ignition": "boolean",
    "speed": "string",
    "acceleration": "string",
    "RPM": "string",
    "movement": {
      "idle": "timespan",
      "moving": "timespan"
    },
    "odometer": "string",
    "fuel": {
      "level": "string",
      "efficiency": "string"
    },
    "DTC": ["string"],
    "tow": {
      "state": "boolean",
      "from": {
        "lat": "double",
        "lon": "double"
      }
    },
    "accident": {
      "state": "boolean",
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "harsh": {
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    }
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "location": {
      "lat": "double",
      "lon": "double"
    },
    "heading": "string",
    "altitude": "uint",
    "accelerometer": {
      "x": "double",
      "y": "double",
      "z": "double"
    },
    "distance": "string",
    "battery": "string",
    "ignition": "boolean",
    "speed": "string",
    "acceleration": "string",
    "RPM": "string",
    "movement": {
      "idle": "timespan",
      "moving": "timespan"
    },
    "odometer": "string",
    "fuel": {
      "level": "string",
      "efficiency": "string"
    },
    "DTC": ["string"],
    "tow": {
      "state": "boolean",
      "from": {
        "lat": "double",
        "lon": "double"
      }
    },
    "accident": {
      "state": "boolean",
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "harsh": {
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    }
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "location": {
      "lat": "double",
      "lon": "double"
    },
    "heading": "string",
    "altitude": "uint",
    "accelerometer": {
      "x": "double",
      "y": "double",
      "z": "double"
    },
    "distance": "string",
    "battery": "string",
    "ignition": "boolean",
    "speed": "string",
    "acceleration": "string",
    "RPM": "string",
    "movement": {
      "idle": "timespan",
      "moving": "timespan"
    },
    "odometer": "string",
    "fuel": {
      "level": "string",
      "efficiency": "string"
    },
    "DTC": ["string"],
    "tow": {
      "state": "boolean",
      "from": {
        "lat": "double",
        "lon": "double"
      }
    },
    "accident": {
      "state": "boolean",
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "harsh": {
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    }
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "bus": "{ 1: J1850 VPW, 2: J1850 PWM, 3: ISO9141_2, 4: KWP2000 Fast Init, 5: ISO15765 CAN 11BIT 500KBaud, 6: ISO15765 CAN 29BIT 500KBaud, 7: ISO15765 CAN 11BIT 250KBaud, 8: ISO15765 CAN 29BIT 250KBaud, 9: KWP2000 5-Baud Init }",
    "battery": "string",
    "VIN": "string",
    "GPS": {
      "strength": "string",
      "accuracy": "string",
      "status": "{ 1: 'off', 2: 'searching', 3: 'connected }",
      "satellites": "string"
    },
    "firmware": {
      "version": "string"
    },
    "configuration": {
      "version": "string"
    },
    "sim": {
      "IMSI": "string",
      "connected": "boolean",
      "strength": "string"
    },
    "state": "{ 1: 'sleep', 2: 'waking', 3: 'standby', 4: 'operational' }"
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "bus": "{ 1: J1850 VPW, 2: J1850 PWM, 3: ISO9141_2, 4: KWP2000 Fast Init, 5: ISO15765 CAN 11BIT 500KBaud, 6: ISO15765 CAN 29BIT 500KBaud, 7: ISO15765 CAN 11BIT 250KBaud, 8: ISO15765 CAN 29BIT 250KBaud, 9: KWP2000 5-Baud Init }",
    "battery": "string",
    "VIN": "string",
    "GPS": {
      "strength": "string",
      "accuracy": "string",
      "status": "{ 1: 'off', 2: 'searching', 3: 'connected }",
      "satellites": "string"
    },
    "firmware": {
      "version": "string"
    },
    "configuration": {
      "version": "string"
    },
    "sim": {
      "IMSI": "string",
      "connected": "boolean",
      "strength": "string"
    },
    "state": "{ 1: 'sleep', 2: 'waking', 3: 'standby', 4: 'operational' }"
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "location": {
      "lat": "double",
      "lon": "double"
    },
    "heading": "string",
    "altitude": "uint",
    "accelerometer": {
      "x": "double",
      "y": "double",
      "z": "double"
    },
    "distance": "string",
    "battery": "string",
    "ignition": "boolean",
    "speed": "string",
    "acceleration": "string",
    "RPM": "string",
    "movement": {
      "idle": "timespan",
      "moving": "timespan"
    },
    "odometer": "string",
    "fuel": {
      "level": "string",
      "efficiency": "string"
    },
    "DTC": ["string"],
    "tow": {
      "state": "boolean",
      "from": {
        "lat": "double",
        "lon": "double"
      }
    },
    "accident": {
      "state": "boolean",
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "harsh": {
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    }
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "location": {
      "lat": "double",
      "lon": "double"
    },
    "heading": "string",
    "altitude": "uint",
    "accelerometer": {
      "x": "double",
      "y": "double",
      "z": "double"
    },
    "distance": "string",
    "battery": "string",
    "ignition": "boolean",
    "speed": "string",
    "acceleration": "string",
    "RPM": "string",
    "movement": {
      "idle": "timespan",
      "moving": "timespan"
    },
    "odometer": "string",
    "fuel": {
      "level": "string",
      "efficiency": "string"
    },
    "DTC": ["string"],
    "tow": {
      "state": "boolean",
      "from": {
        "lat": "double",
        "lon": "double"
      }
    },
    "accident": {
      "state": "boolean",
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "harsh": {
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    }
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "location": {
      "lat": "double",
      "lon": "double"
    },
    "heading": "string",
    "altitude": "uint",
    "accelerometer": {
      "x": "double",
      "y": "double",
      "z": "double"
    },
    "distance": "string",
    "battery": "string",
    "ignition": "boolean",
    "speed": "string",
    "acceleration": "string",
    "RPM": "string",
    "movement": {
      "idle": "timespan",
      "moving": "timespan"
    },
    "odometer": "string",
    "fuel": {
      "level": "string",
      "efficiency": "string"
    },
    "DTC": ["string"],
    "tow": {
      "state": "boolean",
      "from": {
        "lat": "double",
        "lon": "double"
      }
    },
    "accident": {
      "state": "boolean",
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "harsh": {
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    }
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "location": {
      "lat": "double",
      "lon": "double"
    },
    "heading": "string",
    "altitude": "uint",
    "accelerometer": {
      "x": "double",
      "y": "double",
      "z": "double"
    },
    "distance": "string",
    "battery": "string",
    "ignition": "boolean",
    "speed": "string",
    "acceleration": "string",
    "RPM": "string",
    "movement": {
      "idle": "timespan",
      "moving": "timespan"
    },
    "odometer": "string",
    "fuel": {
      "level": "string",
      "efficiency": "string"
    },
    "DTC": ["string"],
    "tow": {
      "state": "boolean",
      "from": {
        "lat": "double",
        "lon": "double"
      }
    },
    "accident": {
      "state": "boolean",
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    },
    "harsh": {
      "profile": [
        {
          "x": "double",
          "y": "double",
          "z": "double"
        }
      ]
    }
  });

  ({
    "id": "string",
    "sequence": "uint",
    "opcode": "string",
    "eventTime": "datetime",
    "bus": "{ 1: J1850 VPW, 2: J1850 PWM, 3: ISO9141_2, 4: KWP2000 Fast Init, 5: ISO15765 CAN 11BIT 500KBaud, 6: ISO15765 CAN 29BIT 500KBaud, 7: ISO15765 CAN 11BIT 250KBaud, 8: ISO15765 CAN 29BIT 250KBaud, 9: KWP2000 5-Baud Init }",
    "battery": "string",
    "VIN": "string",
    "GPS": {
      "strength": "string",
      "accuracy": "string",
      "status": "{ 1: 'off', 2: 'searching', 3: 'connected }",
      "satellites": "string"
    },
    "firmware": {
      "version": "string"
    },
    "configuration": {
      "version": "string"
    },
    "sim": {
      "IMSI": "string",
      "connected": "boolean",
      "strength": "string"
    },
    "state": "{ 1: 'sleep', 2: 'waking', 3: 'standby', 4: 'operational' }"
  });

}).call(this);

//# sourceMappingURL=packets.js.map
