// Generated by CoffeeScript 1.10.0
(function() {
  var BIOTON, IOTON, PIOTON;

  IOTON = './src/ioton';

  PIOTON = './src/pioton';

  BIOTON = './src/bioton';

  module.exports = {
    ioton: IOTON,
    pioton: PIOTON,
    bioton: BIOTON
  };

}).call(this);

//# sourceMappingURL=ioton.js.map
