// Generated by CoffeeScript 1.8.0
(function() {
  var PrettyJSON;

  module.exports = PrettyJSON = (function() {
    function PrettyJSON() {}

    PrettyJSON.prototype.replacer = function(match, pIndent, pKey, pVal, pEnd) {
      var key, r, str, val;
      key = '<span class=json-key>';
      val = '<span class=json-value>';
      str = '<span class=json-string>';
      r = pIndent || '';
      if (pKey) {
        r = r + key + pKey.replace(/[": ]/g, '') + '</span>: ';
      }
      if (pVal) {
        r = r + (pVal[0] === '"' ? str : val) + pVal + '</span>';
      }
      return r + (pEnd || '');
    };

    PrettyJSON.prototype.prettyPrint = function(obj) {
      var jsonLine;
      jsonLine = /^( *)("[\w]+": )?("[^"]*"|[\w.+-]*)?([,[{])?$/mg;
      return JSON.stringify(obj, null, 3).replace(/&/g, '&amp;').replace(/\\"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(jsonLine, this.replacer);
    };

    return PrettyJSON;

  })();

}).call(this);

//# sourceMappingURL=PrettyJSON.js.map
