// Generated by CoffeeScript 1.10.0
(function() {
  var Context, Loggly, debug, environment, error, error1;

  try {
    environment = process.env.PARAM1;
    if (environment == null) {
      environment = 'Local';
    }
    debug = process.env.DEBUG === 'true' || false;
    Context = {
      env: environment,
      debug: debug
    };
    if (environment === 'Local') {
      Context.logger = console;
      Context.loadTest = false;
      Context.debug = true;
    } else {
      Loggly = require('loggly');
      Context.logger = Loggly.createClient({
        token: "a9ab4898-5e03-4144-bd51-fab7a9bc42ec",
        subdomain: "mojio",
        tags: ["NodeJS", "IOTONNodeServer", environment],
        json: true
      });
    }
    Context.logger.log("IOTON Node Server starting up... " + Context.env);
    Context.logger.log("Debug?: " + Context.debug);
    Context.logger.log("Logger?: " + (Context.env === 'Local' ? "Console" : "Loggly"));
    module.exports = Context;
  } catch (error1) {
    error = error1;
    Context.logger.log("Error in Context: " + error);
  }

}).call(this);

//# sourceMappingURL=Context.js.map
