// Generated by CoffeeScript 1.10.0
(function() {
  var Bioton, Ioton,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Ioton = require('./Ioton');

  module.exports = Bioton = (function(superClass) {
    extend(Bioton, superClass);

    function Bioton() {
      return Bioton.__super__.constructor.apply(this, arguments);
    }

    Bioton.prototype.encode = function(object) {
      return this._type.encode(object);
    };

    Bioton.prototype.decode = function(buffer) {
      return this._type.decode(buffer);
    };

    return Bioton;

  })(Ioton);

}).call(this);

//# sourceMappingURL=Bioton.js.map
