// Generated by CoffeeScript 1.8.0
(function() {
  var ReadState;

  module.exports = ReadState = (function() {
    function ReadState(buffer) {
      this._buffer = buffer;
      this._offset = 0;
    }

    ReadState.prototype.peekUInt8 = function() {
      return this._buffer.readUInt8(this._offset);
    };

    ReadState.prototype.readUInt8 = function() {
      return this._buffer.readUInt8(this._offset++);
    };

    ReadState.prototype.readUInt16 = function() {
      var r;
      r = this._buffer.readUInt16BE(this._offset);
      this._offset += 2;
      return r;
    };

    ReadState.prototype.readUInt32 = function() {
      var r;
      r = this._buffer.readUInt32BE(this._offset);
      this._offset += 4;
      return r;
    };

    ReadState.prototype.readDouble = function() {
      var r;
      r = this._buffer.readDoubleBE(this._offset);
      this._offset += 8;
      return r;
    };

    ReadState.prototype.readBuffer = function(length) {
      var r;
      if (this._offset + length > this._buffer.length) {
        throw new RangeError('Trying to access beyond buffer length');
      }
      r = this._buffer.slice(this._offset, this._offset + length);
      this._offset += length;
      return r;
    };

    ReadState.prototype.hasEnded = function() {
      return this._offset === this._buffer.length;
    };

    return ReadState;

  })();

}).call(this);

//# sourceMappingURL=ReadState.js.map
