// Generated by CoffeeScript 1.10.0
(function() {
  var makeValue;

  modules.exports = Class(Typer({
    constructor: function() {}
  }, makeValue = function(value, type) {
    switch (type) {
      case "string":
        return value.toString();
      case 'number':
      case 'uint':
      case 'int':
      case 'float':
        return parseFloat(value);
      case "boolean":
        return value === 'true';
      default:
        return value;
    }
  }));

}).call(this);

//# sourceMappingURL=Typer.js.map
